rewarded add has been successfully applied
nooralibutt/easy-ads pull request #4
Opened 2021-09-15 09:48 UTC by Abdullahjavaid0331

2021-09-15 12:20 UTC, rmahmadkhan requested changes

2021-09-15 12:20 UTC, rmahmadkhan commented on lib/screens/country_list_screen.dart
> +  EasyAdmobRewardedAd easyAdmobRewardedAd = EasyAdmobRewardedAd();
make it nullable

2021-09-15 12:25 UTC, nooralibutt requested changes

2021-09-16 08:20 UTC, rmahmadkhan approved these changes

2021-09-16 08:36 UTC, mhanzla80 approved these changes

2021-09-16 08:38 UTC, nooralibutt approved these changes

2021-09-16 08:38 UTC, merged